/**
 * The Access_Gate decision, as a plain function over plain facts
 * (Requirements 8.2, 8.3, 8.9, 8.10).
 *
 * `src/start.ts` registers the global request middleware; this module holds the
 * whole rule it applies. The split exists so the decision can be exercised
 * without a socket, a server, or a browser: {@link evaluateGate} takes the
 * {@link Auth} seam, a pathname, a handler type, and a raw `Cookie:` header
 * string, and returns a value. {@link gateRejectionResponse} is the only part
 * that builds a `Response`.
 *
 * ## What the rejection response holds
 *
 * A rejection carries exactly three things: a status, the
 * {@link SESSION_REQUIRED_MESSAGE}, and the {@link LOGIN_PATH} it points at. No
 * Member_Registry value, no Redemption_History value, and no character of the
 * Shared_Passphrase — this module never reads the passphrase, so it cannot leak
 * one, and it contains no logging call at all (Requirement 8.10).
 *
 * ## Why rejecting here is "before any store read"
 *
 * Request middleware runs before the request reaches a handler. Returning a
 * `Response` from it short-circuits the chain: neither the router nor a server
 * function is invoked, so no store module is loaded, no Member_Registry or
 * Redemption_History read happens, and `RunCoordinator.start` is never called
 * (Requirement 8.3). Ordering is the mechanism — this module deliberately
 * imports nothing from `@/server/store` or `@/server/run`, so it could not read
 * or start anything even by accident.
 *
 * ## The exemptions, and why each one exists
 *
 * A gate that covered the login submission would lock everyone out: nobody
 * could ever obtain a Session. So the exemption list has to exist, and it has to
 * stay as small as possible, because everything on it is reachable without a
 * Session. Two kinds of entry, both restricted to `handlerType: "router"` so
 * that **no server function is ever exempt**:
 *
 * 1. {@link LOGIN_PATH} exactly. The login document, and a form submission
 *    posted to the same path. This is the one entry that must accept a POST.
 * 2. The static files needed to render that document: the built client bundle,
 *    the built asset directory, the three files in `public/`, and the dev
 *    server's module-graph prefixes. These are build artifacts served
 *    identically to every visitor; they hold no roster value, no history value,
 *    and no secret, because every environment read lives in a `.server.ts`
 *    module that the client build excludes. Without them the login page loads
 *    as unstyled, unhydrated HTML.
 *
 * Not exempt, deliberately:
 *
 * - **Every server function.** Requests under the server-function base arrive
 *   with `handlerType: "serverFn"` and {@link isGateExemptPath} returns false
 *   for them unconditionally. That is the data boundary: `listMembers`,
 *   `listHistory`, and `redeem` are independently reachable endpoints, and they
 *   are what a stranger would call.
 * - **Every other document**, `/` included. An SSR'd roster or history page
 *   would embed the very values Requirement 8.3 says to withhold.
 * - **`/@fs/`**, the dev server's arbitrary-file route. It can serve any file
 *   inside the Vite root, `.env` and `data/store.json` included. The dev server
 *   answers those requests before this middleware ever runs, so listing the
 *   prefix would buy nothing and would read as an endorsement.
 *
 * ## Consequence for the login submission
 *
 * A server function's URL is `<base>/<functionId>`, and `functionId` is
 * generated by the compiler — a SHA-256 hash in a build, a base64url blob in
 * dev. It cannot be written into an allowlist by hand. So the login submission
 * must arrive at {@link LOGIN_PATH} itself (a `POST` handler on the `/login`
 * file route, or a plain HTML form posting there), not as a server function
 * call. The alternative, if a server function is ever wanted for it, is to
 * configure a stable id generator (`tanstackStart({ serverFns: {
 * generateFunctionId } })`) and add that one id here explicitly.
 */

import { LOGIN_PATH, SESSION_REQUIRED_MESSAGE } from "@/server/auth.server"

import type { Auth, SessionVerification } from "@/server/auth.server"

/** Which Start handler a request was heading for. */
export type GateHandlerType = "router" | "serverFn"

/**
 * The part of {@link Auth} the decision needs: whether the gate is armed, and
 * the verdict on a `Cookie:` header. Narrowed so a test can pass a two-function
 * literal, and so this module cannot come to depend on the passphrase
 * comparison or on session issuance.
 */
export type GateAuth = Pick<
  Auth,
  "passphraseRequired" | "verifySessionCookieHeader"
>

/** Everything about a request that the decision looks at. */
export interface GateRequestFacts {
  /** URL pathname, already normalized by URL parsing. No query, no hash. */
  readonly pathname: string
  /** Handler the request was heading for. */
  readonly handlerType: GateHandlerType
  /** Raw `Cookie:` header value, or null when the request carried none. */
  readonly cookieHeader: string | null | undefined
}

/** Input of {@link evaluateGate}. */
export interface GateInput extends GateRequestFacts {
  /** The Access_Gate seam. Injected, so tests need no process-wide state. */
  readonly auth: GateAuth
}

/** Why a request was admitted. */
export type GateAdmitReason =
  /** No Shared_Passphrase is configured, so the gate is off (Requirement 8.9). */
  | "gate-disabled"
  /** The path is on the exemption list, so the login page stays reachable. */
  | "exempt-path"
  /** The request carried a valid Session (Requirement 8.2). */
  | "valid-session"

/** An admitted request. */
export interface GateAdmission {
  readonly kind: "admit"
  readonly reason: GateAdmitReason
}

/**
 * A refused request (Requirement 8.3).
 *
 * Every field is either a status, the fixed {@link SESSION_REQUIRED_MESSAGE}, or
 * the fixed {@link LOGIN_PATH}. Nothing here is derived from the Member_Registry,
 * the Redemption_History, or the Shared_Passphrase.
 */
export interface GateRejection {
  readonly kind: "reject"
  /** Why the Session was not accepted. Never `"valid"`. */
  readonly reason: Exclude<SessionVerification["kind"], "valid">
  /** HTTP status of the response. */
  readonly status: number
  /** Always {@link SESSION_REQUIRED_MESSAGE}. */
  readonly message: string
  /** Always {@link LOGIN_PATH}: where the sender submits the passphrase. */
  readonly loginPath: string
  /** `Location:` value for a document request; null for a server function. */
  readonly location: string | null
  /** Exact response body. */
  readonly body: string
  /** `Content-Type:` of {@link body}. */
  readonly contentType: string
}

/** The whole result of the decision. */
export type GateDecision = GateAdmission | GateRejection

/**
 * Status returned to a server-function call made without a Session. 401 rather
 * than a redirect: the caller is `fetch`, which would follow a redirect and get
 * an HTML document where it expected a serialized result.
 */
export const SESSION_REQUIRED_STATUS = 401

/**
 * Status returned to a document request made without a Session. 303 sends the
 * browser to {@link LOGIN_PATH} with a GET whatever the original method was,
 * which is precisely "directs the sender to submit the Shared_Passphrase".
 */
export const SESSION_REQUIRED_REDIRECT_STATUS = 303

/** Machine-readable code on the server-function rejection body. */
export const SESSION_REQUIRED_CODE = "SESSION_REQUIRED"

/**
 * Paths that stay reachable without a Session, matched exactly.
 *
 * `/login` is the only entry that exists for the gate's own sake; the other
 * three are the files in `public/`, which browsers and crawlers request
 * unprompted while the login page loads.
 */
export const GATE_EXEMPT_PATHS: readonly string[] = [
  LOGIN_PATH,
  "/favicon.ico",
  "/manifest.json",
  "/robots.txt",
]

/**
 * Prefixes that stay reachable without a Session, each ending in `/` so that a
 * route named `/_buildish` cannot slip through a `/_build` prefix.
 *
 * - `/_build/` — the client bundle base configured by TanStack Start.
 * - `/assets/` — the built client asset directory (JS, CSS, fonts).
 * - `/@vite/`, `/@id/`, `/node_modules/`, `/src/` — the dev server's module
 *   graph. The dev server normally answers these itself, before this middleware
 *   runs; they are listed so a login page that reaches the middleware in dev is
 *   still able to load its modules. In a build these paths hold nothing.
 */
export const GATE_EXEMPT_PATH_PREFIXES: readonly string[] = [
  "/_build/",
  "/assets/",
  "/@vite/",
  "/@id/",
  "/node_modules/",
  "/src/",
]

/** Exact paths a dev-only request may carry with no trailing segment. */
const GATE_EXEMPT_DEV_PATHS: readonly string[] = ["/@react-refresh"]

/** Drops a single trailing slash, so `/login/` matches `/login`. */
function withoutTrailingSlash(pathname: string): string {
  return pathname.length > 1 && pathname.endsWith("/")
    ? pathname.slice(0, -1)
    : pathname
}

/**
 * True when `pathname` may be served without a Session.
 *
 * A server function is never exempt: the `handlerType` check is the first thing
 * this function does, and it is what keeps the exemption list from ever opening
 * the data boundary.
 */
export function isGateExemptPath(
  pathname: string,
  handlerType: GateHandlerType
): boolean {
  if (handlerType !== "router") {
    return false
  }

  const path = withoutTrailingSlash(pathname)
  if (GATE_EXEMPT_PATHS.includes(path)) {
    return true
  }
  if (GATE_EXEMPT_DEV_PATHS.includes(path)) {
    return true
  }
  return GATE_EXEMPT_PATH_PREFIXES.some((prefix) => pathname.startsWith(prefix))
}

/** The body a refused server-function call receives. */
function serverFnRejectionBody(): string {
  return JSON.stringify({
    error: SESSION_REQUIRED_CODE,
    message: SESSION_REQUIRED_MESSAGE,
    loginPath: LOGIN_PATH,
  })
}

/**
 * Builds the rejection for one refused request.
 *
 * Not the {@link Envelope} shape the server functions return, on purpose: the
 * request never reached a server function, and a caller that unwrapped this as
 * an application-level failure would report "the roster could not be read"
 * instead of "sign in".
 */
function reject(
  reason: GateRejection["reason"],
  handlerType: GateHandlerType
): GateRejection {
  const forServerFn = handlerType === "serverFn"
  return {
    kind: "reject",
    reason,
    status: forServerFn
      ? SESSION_REQUIRED_STATUS
      : SESSION_REQUIRED_REDIRECT_STATUS,
    message: SESSION_REQUIRED_MESSAGE,
    loginPath: LOGIN_PATH,
    location: forServerFn ? null : LOGIN_PATH,
    body: forServerFn ? serverFnRejectionBody() : SESSION_REQUIRED_MESSAGE,
    contentType: forServerFn
      ? "application/json; charset=utf-8"
      : "text/plain; charset=utf-8",
  }
}

/**
 * The Access_Gate decision (Requirements 8.2, 8.3, 8.9).
 *
 * In order:
 *
 * 1. no Shared_Passphrase configured ⇒ admit, whatever the request carries
 *    (Requirement 8.9);
 * 2. exempt path ⇒ admit, so the login page and its assets stay reachable;
 * 3. valid Session ⇒ admit (Requirement 8.2);
 * 4. anything else ⇒ reject, with the reason the verification gave
 *    (Requirement 8.3).
 *
 * Reads no environment variable and performs no I/O, so it is safe to call on
 * every request and trivial to test.
 */
export function evaluateGate(input: GateInput): GateDecision {
  const { auth, pathname, handlerType, cookieHeader } = input

  if (!auth.passphraseRequired()) {
    return { kind: "admit", reason: "gate-disabled" }
  }
  if (isGateExemptPath(pathname, handlerType)) {
    return { kind: "admit", reason: "exempt-path" }
  }

  const verification = auth.verifySessionCookieHeader(cookieHeader)
  if (verification.kind === "valid") {
    return { kind: "admit", reason: "valid-session" }
  }
  return reject(verification.kind, handlerType)
}

/**
 * Turns a {@link GateRejection} into the response the sender receives.
 *
 * `Cache-Control: no-store` because a cached rejection would keep showing after
 * a Session was obtained, and a cached redirect is worse still. No `Set-Cookie`:
 * the gate reads the Session, it never writes one.
 */
export function gateRejectionResponse(rejection: GateRejection): Response {
  const headers = new Headers({
    "Content-Type": rejection.contentType,
    "Cache-Control": "no-store",
  })
  if (rejection.location !== null) {
    headers.set("Location", rejection.location)
  }
  return new Response(rejection.body, {
    status: rejection.status,
    headers,
  })
}
