/**
 * The `/login` document and the passphrase submission endpoint
 * (Requirements 8.3, 8.4, 8.5, 8.9, 8.10).
 *
 * ## Why the submission is a route handler and not a server function
 *
 * `src/server/gate.server.ts` exempts exactly the paths it can name, and it
 * never exempts a server function. A server function's URL is
 * `<base>/<functionId>`, where `functionId` is generated by the compiler — a
 * SHA-256 hash in a build, a base64url blob in dev — so it cannot be written
 * into the exemption list by hand. A login server function would therefore be
 * gated, and nobody could ever obtain a Session. Posting the form to
 * `/login` itself makes the request pathname the literal string the gate
 * already exempts, and the framework routes it to the `POST` handler below
 * before the router renders anything.
 *
 * ## What crosses to the browser
 *
 * The Shared_Passphrase is read only inside {@link getAuth}, on the server, and
 * appears in no field of {@link LoginView}: the loader hands the client two
 * booleans and two message strings, each of which is a module-level constant
 * from `auth.server.ts` (Requirement 8.10). The submitted value is never
 * echoed either — a rejected submission redirects to `/login?error=<code>`
 * carrying a fixed code, and the `GET` handler is the only place that turns a
 * code into a sentence. An unrecognized code produces no message at all, so a
 * crafted query string cannot put attacker-chosen text on the page.
 *
 * ## Works without JavaScript
 *
 * The form is a plain `method="post"` HTML form and every outcome is a 303
 * redirect, so the whole flow — submit, land back with an error, or land on `/`
 * with a Session — runs with scripting disabled. 303 in particular is what
 * turns the POST into a GET of the redirect target.
 *
 * The `server` block, and with it the `auth.server.ts` import, is deleted from
 * this module in the client build (the Start router plugin removes the `ssr`,
 * `server`, and `headers` route options for the client environment), which is
 * what keeps a `.server.ts` module out of the browser bundle.
 */

import { createFileRoute } from "@tanstack/react-router"

import { Alert, AlertDescription } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import {
  GATE_DISABLED_MESSAGE,
  INCORRECT_PASSPHRASE_MESSAGE,
  LOGIN_PATH,
  THROTTLED_MESSAGE,
  getAuth,
} from "@/server/auth.server"

/**
 * What a gate rejection says the sender must do, mirrored from
 * `gate.server.ts`'s `GateRejectionNeeds`. Declared locally rather than
 * imported — even as a type — so this client route reaches nothing in a
 * `.server` module: the build's import-protection denies a `.server` import
 * from a route, and keeping the union here (it is two fixed strings) keeps
 * `login.tsx` free of `gate.server` entirely. `src/server/gate.server.ts`
 * remains the source of truth for the values the server emits; a drift between
 * the two would surface as a type error where the gate builds its rejection.
 */
type GateRejectionNeeds = "passphrase" | "passphrase-and-sign-in"

/**
 * Path of the sign-in document a Requirement 7.8 rejection points an
 * unauthenticated sender to. A literal rather than an import of `SIGN_IN_PATH`,
 * because that constant lives in `gate.server.ts`, a `.server` module the
 * browser bundle must not load; `src/routes/sign-in.tsx` declares the same path.
 * This mirrors the local `LOGIN_PATH` literal above, kept for the same reason.
 */
const SIGN_IN_PATH = "/sign-in"

/** Name of the form field holding the submitted value. */
const PASSPHRASE_FIELD = "passphrase"

/** Query parameter naming a failed submission. */
const ERROR_PARAM = "error"

/**
 * Query parameter carrying the gate's {@link GateRejectionNeeds} discriminator,
 * so the page can say whether the passphrase alone is enough (a `member`,
 * Requirement 7.2) or a sign-in is also required (an `anonymous`/`unknown`
 * sender, Requirement 7.8).
 */
const NEEDS_PARAM = "needs"

/** Code for an incorrect submission (Requirement 8.5). */
const ERROR_INCORRECT = "incorrect"

/** Code for a submission refused by the throttle (Requirement 8.8). */
const ERROR_THROTTLED = "throttled"

/** `id` of the error message, referenced by the field's `aria-describedby`. */
const ERROR_ELEMENT_ID = "passphrase-error"

/**
 * The `needs` value assumed when the query carries none, or carries a value
 * this route does not recognize: the safe superset. Offering both the
 * passphrase and sign-in can never lock a sender out — a member who only needs
 * the passphrase can ignore the sign-in link — whereas the narrower
 * "passphrase" copy would hide sign-in from a sender who needs it. This mirrors
 * how {@link errorMessage} maps an unknown code to null (Requirement 8.10): an
 * attacker-chosen query value selects one of two fixed sentences, never text of
 * its own.
 */
const DEFAULT_NEEDS: GateRejectionNeeds = "passphrase-and-sign-in"

/**
 * Where a granted Session lands. The redemption page, which is what the sender
 * was after when the gate turned them away.
 */
const AFTER_LOGIN_PATH = "/"

/**
 * Everything the login document renders. No passphrase, no length, no echo of
 * the submitted value (Requirement 8.10).
 */
interface LoginView {
  /** False when no Shared_Passphrase is configured (Requirement 8.9). */
  readonly passphraseRequired: boolean
  /** A fixed failure message, or null. Never derived from the submission. */
  readonly error: string | null
  /** A fixed informational message, or null. */
  readonly notice: string | null
  /**
   * What the sender must do to be admitted (Requirements 7.2, 7.8). Drives the
   * sign-in link's copy; one of two fixed discriminator values, never a value
   * echoed from the query.
   */
  readonly needs: GateRejectionNeeds
}

/**
 * What the component renders when no server handler ran for this navigation —
 * a client-side navigation to `/login` from inside the app. Showing the form is
 * the safe default: submitting it is what discovers the real state.
 */
const CLIENT_NAVIGATION_VIEW: LoginView = {
  passphraseRequired: true,
  error: null,
  notice: null,
  needs: DEFAULT_NEEDS,
}

/**
 * The message for a failure code, or null when the code is absent or not one
 * this route issues. Only these two sentences can ever reach the page.
 */
function errorMessage(code: string | null): string | null {
  if (code === ERROR_INCORRECT) {
    return INCORRECT_PASSPHRASE_MESSAGE
  }
  if (code === ERROR_THROTTLED) {
    return THROTTLED_MESSAGE
  }
  return null
}

/**
 * The {@link GateRejectionNeeds} a query value names, or {@link DEFAULT_NEEDS}
 * when the value is absent or is not one the gate issues. Like
 * {@link errorMessage}, this is the only place a query value turns into
 * behaviour, and it can only ever select between the two fixed discriminator
 * values — a crafted query cannot put attacker-chosen text on the page
 * (Requirement 8.10).
 */
function needsFrom(value: string | null): GateRejectionNeeds {
  return value === "passphrase" ? "passphrase" : DEFAULT_NEEDS
}

/**
 * The instruction shown beside the sign-in link, chosen by the discriminator.
 * A `member` needs only the passphrase (Requirement 7.2); an anonymous or
 * unknown sender needs both the passphrase and a sign-in (Requirement 7.8).
 * Both are fixed sentences.
 */
function signInCopy(needs: GateRejectionNeeds): string {
  return needs === "passphrase"
    ? "Already signed in? Submit the passphrase above to continue."
    : "New here? Submit the passphrase above and sign in to continue."
}

/**
 * The sender the failed-attempt throttle counts against (Requirement 8.8).
 *
 * Behind a reverse proxy — the deployment this app documents — the first entry
 * of `X-Forwarded-For` is the client address. Exposed directly, the header is
 * whatever the client sent, so it can be varied to spread attempts across
 * buckets; the throttle is a brake on casual guessing, not a substitute for
 * keeping the port off the public internet. An absent header yields an empty
 * string, which `auth.server.ts` normalizes to a single shared bucket rather
 * than an unthrottled lane.
 */
function senderOf(request: Request): string {
  const forwardedFor = request.headers.get("x-forwarded-for")
  if (forwardedFor !== null) {
    return forwardedFor.split(",")[0]?.trim() ?? ""
  }
  return request.headers.get("x-real-ip")?.trim() ?? ""
}

/**
 * A 303 redirect, optionally granting or clearing the session cookie.
 *
 * 303 rather than 302: it tells the browser to GET `location` whatever method
 * the original request used, which is exactly what a form POST needs.
 * `no-store` because both the rejection and the grant are one-shot.
 */
function seeOther(location: string, setCookie?: string): Response {
  const headers = new Headers({
    Location: location,
    "Cache-Control": "no-store",
  })
  if (setCookie !== undefined) {
    headers.append("Set-Cookie", setCookie)
  }
  return new Response(null, { status: 303, headers })
}

/** `/login?error=<code>`. */
function loginPathWithError(code: string): string {
  return `${LOGIN_PATH}?${ERROR_PARAM}=${code}`
}

export const Route = createFileRoute("/login")({
  server: {
    handlers: ({ createHandlers }) =>
      createHandlers({
        /**
         * Renders the document. The gate state and any failure message are
         * decided here, on the server, and handed to the loader as context;
         * `next()` then lets the router render the component below.
         */
        GET: ({ request, next }) => {
          const passphraseRequired = getAuth().passphraseRequired()
          const params = new URL(request.url).searchParams
          const code = params.get(ERROR_PARAM)
          return next({
            context: {
              login: {
                passphraseRequired,
                error: passphraseRequired ? errorMessage(code) : null,
                notice: passphraseRequired ? null : GATE_DISABLED_MESSAGE,
                needs: needsFrom(params.get(NEEDS_PARAM)),
              } satisfies LoginView,
            },
          })
        },

        /**
         * The submission (Requirements 8.4, 8.5).
         *
         * A match grants the Session by setting the cookie the outcome carries
         * and sending the sender to the app. Every other outcome redirects back
         * to `/login` with a fixed code — no Session, no `Set-Cookie`, and no
         * word about the submitted value.
         */
        POST: async ({ request }) => {
          const submitted = (await request.formData()).get(PASSPHRASE_FIELD)
          const outcome = getAuth().submitPassphrase({
            sender: senderOf(request),
            submitted: typeof submitted === "string" ? submitted : "",
          })

          switch (outcome.kind) {
            case "granted":
              return seeOther(AFTER_LOGIN_PATH, outcome.setCookie)
            case "rejected":
              return seeOther(loginPathWithError(ERROR_INCORRECT))
            case "throttled":
              return seeOther(loginPathWithError(ERROR_THROTTLED))
            case "gate-disabled":
              /*
               * Nothing to submit: the GET handler will report the gate is off
               * and the page will say so (Requirement 8.9).
               */
              return seeOther(LOGIN_PATH)
          }
        },
      }),
  },

  loader: ({ serverContext }): LoginView =>
    serverContext?.login ?? CLIENT_NAVIGATION_VIEW,

  component: LoginPage,
})

function LoginPage() {
  const { passphraseRequired, error, notice, needs } = Route.useLoaderData()

  return (
    <main className="flex min-h-svh items-center justify-center p-6">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>Sign in</CardTitle>
          <CardDescription>
            This deployment is shared with your group.
          </CardDescription>
        </CardHeader>

        <CardContent>
          {passphraseRequired ? (
            /*
             * A plain HTML form posting to this very path: no JavaScript, and a
             * pathname the Access_Gate exempts. `autoComplete` lets a password
             * manager fill the shared value.
             */
            <form method="post" action="/login" className="flex flex-col gap-3">
              <div className="flex flex-col gap-1.5">
                <label htmlFor={PASSPHRASE_FIELD} className="font-medium">
                  Shared passphrase
                </label>
                <Input
                  id={PASSPHRASE_FIELD}
                  name={PASSPHRASE_FIELD}
                  type="password"
                  autoComplete="current-password"
                  required
                  aria-invalid={error !== null}
                  aria-describedby={
                    error !== null ? ERROR_ELEMENT_ID : undefined
                  }
                />
              </div>

              {error !== null ? (
                <Alert variant="destructive" id={ERROR_ELEMENT_ID}>
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              ) : null}

              <Button type="submit">Continue</Button>
            </form>
          ) : (
            <Alert>
              <AlertDescription>{notice}</AlertDescription>
            </Alert>
          )}

          {/*
           * The sign-in link, always offered: it is safe whatever the sender
           * needs (a member can ignore it), and a Requirement 7.8 rejection
           * needs it reachable. Its instruction is chosen by `needs` — one of
           * two fixed sentences (Requirements 7.2, 7.8) — while the link itself
           * is a plain anchor to SIGN_IN_PATH, so the whole flow works with
           * JavaScript disabled.
           */}
          <div className="mt-4 flex flex-col gap-2 border-t pt-4">
            <p className="text-sm text-muted-foreground">{signInCopy(needs)}</p>
            <Button asChild variant="outline">
              <a href={SIGN_IN_PATH}>Sign in with Google</a>
            </Button>
          </div>
        </CardContent>
      </Card>
    </main>
  )
}
